# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyagentCli < Formula
  desc "Lazy TUI for monitoring coding agent sessions"
  homepage "https://github.com/illegalstudio/lazyagent"
  version "0.13.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.13.3/lazyagent-cli_0.13.3_darwin_amd64.zip"
      sha256 "3b877c619ea8fca696904c3b3dda006c55a3e3d4b37b7832bf04fa340a8d9093"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.13.3/lazyagent-cli_0.13.3_darwin_arm64.zip"
      sha256 "d19513c6d571d75a67270fd6686d2cd41b4ea2a0df441d88c8611a31024f35f8"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.13.3/lazyagent-cli_0.13.3_linux_amd64.tar.gz"
      sha256 "3b2c87cc9d4056cce4ddb1e0419bd35bbf0e7aac849a65a81c22bbd2d0ce5da7"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.13.3/lazyagent-cli_0.13.3_linux_arm64.tar.gz"
      sha256 "6a0548aa993ea02856e1d959ae3bf2da1f6bd8b8a8fcee6e01c3be66de0c7c84"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  def caveats
    <<~EOS
      Installs the `lazyagent` command (CLI-only build, no GUI).
    EOS
  end
end
