# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyagentCli < Formula
  desc "Lazy TUI for monitoring coding agent sessions"
  homepage "https://github.com/illegalstudio/lazyagent"
  version "0.14.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.14.2/lazyagent-cli_0.14.2_darwin_amd64.zip"
      sha256 "0fe23f6c6247a83a5aabcee26821b03c2cbc6038ad677f439ae06716b230ff63"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.14.2/lazyagent-cli_0.14.2_darwin_arm64.zip"
      sha256 "af94741dacf43afdca3d54f2ff1fa44a8ab77ccef2c35ad34a66dad8c8861c72"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.14.2/lazyagent-cli_0.14.2_linux_amd64.tar.gz"
      sha256 "486ed4b1b1c21a32cf8234783e04c5079372dd9d12a00c83be024d1e3cc79a5a"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.14.2/lazyagent-cli_0.14.2_linux_arm64.tar.gz"
      sha256 "5d8e4bfa9a611ae657319b269df78928edb847ef6af1e61f922bb34d9a8afddd"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  def caveats
    <<~EOS
      Installs the `lazyagent` command (CLI-only build, no GUI).
    EOS
  end
end
