# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyagentCli < Formula
  desc "Lazy TUI for monitoring coding agent sessions"
  homepage "https://github.com/illegalstudio/lazyagent"
  version "0.15.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.15.4/lazyagent-cli_0.15.4_darwin_amd64.zip"
      sha256 "0cf65707ef1d2f3d47759aee5c32ae3963966f83f8d9c489a291ebcdceed2817"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.15.4/lazyagent-cli_0.15.4_darwin_arm64.zip"
      sha256 "61afddfaab1e97a7848a6b20dfa60e2675bbe39e0b7bdffe28575d71a72f4d9b"

      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.15.4/lazyagent-cli_0.15.4_linux_amd64.tar.gz"
      sha256 "ba5054c4c82290da0fd96f9a4fbc420a77c1100dfbd2750fc7e66b3ff7ba8170"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/illegalstudio/lazyagent/releases/download/v0.15.4/lazyagent-cli_0.15.4_linux_arm64.tar.gz"
      sha256 "47562dfcc75f536d05399358796a3ee5a8a81115d845e6d46a35d69638d8997a"
      define_method(:install) do
        bin.install "lazyagent"
      end
    end
  end

  def caveats
    <<~EOS
      Installs the `lazyagent` command (CLI-only build, no GUI).
    EOS
  end
end
