# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggg" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "81ebe969ecabd91a5d81beca31cc28f10d1f569b0d2cb9a05863f3402c939595"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "b582065c26544ed5a6e5ee48f2df80469b669a9209cbbf7d0c0acf080b77f384"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0941e733716f237c9cc7e1ff1e2034afd2130da5640fe4a1bbdae54d108cea8"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "522ae02c870a196f979af8a12b59511efa3286de97425ccae517d80d6b194455"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ggg"
  desc "Clone and manage git repositories from a YAML configuration file"
  homepage "https://github.com/illegalstudio/ggg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggg"

  # No zap stanza required

end
