# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggg" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "efa195424bf690a1607c5fcf96c32ea8852d15d96829a7d8eb7db094dd30f698"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d53060413658a377d4996df105f7248626dbfff3e90ca7524910b79d7ec4f8a"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4bd034eccad908294375d78e47009782c6b03a6f3cdd2de811ab839ed814ab6d"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c953475c0303fa5ef70ca782d489baecad14f16c43b3be4f6065aaf39bc6ecb3"
      url "https://github.com/illegalstudio/ggg/releases/download/v#{version}/ggg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ggg"
  desc "Clone and manage git repositories from a YAML configuration file"
  homepage "https://github.com/illegalstudio/ggg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggg"

  # No zap stanza required

end
