# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggw" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "14dc5f58387fe7534fa86b01f8d8be9d5aacec389386783bfbf55c43e2cae955"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b08a89de801e07bcdea184a115ab60a88ca1c1df6a019b7011309f8a8164845"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09a62cfd353a8ff106a8949130a5d230d933c43fb160db2c9e1fdad11c8e7da9"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a139df310dcd7edc400e5819f1f37b5ec49f855e32e9b882d4a3245745e2cde"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ggw"
  desc "Git worktrees, ergonomic — store all worktrees of all your repos in a predictable location"
  homepage "https://github.com/illegalstudio/ggw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggw"

  # No zap stanza required

end
