# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggw" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "ff84a57fd2ccfbdca0a8ef37250208867843e8ecbae9f59ceac92a273e441781"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "fae41adba82ba70edf243a0229fae6ad8c1fe376782e2c66f9b84e7f212b800b"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0385a0617c38b19de61ca687a9d2d575074a03d081adaab55d9c00805d842a0"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfc100657dbabe48378740b7510ecf92144ba80955d8271be03eb61edaa01f56"
      url "https://github.com/illegalstudio/ggw/releases/download/v#{version}/ggw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ggw"
  desc "Git worktrees, ergonomic — store all worktrees of all your repos in a predictable location"
  homepage "https://github.com/illegalstudio/ggw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggw"

  # No zap stanza required

end
