# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  app "Lazyagent.app"

  version "0.13.3"

  on_macos do
    sha256 "0a79a25331c938ebfe4f8f5708b2a78515ecd744e01e22a69670240f57f091cd"
    url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/Lazyagent_#{version}_darwin_universal.zip"
  end

  name "lazyagent"
  desc "Desktop app for monitoring coding agent sessions (includes the CLI)"
  homepage "https://github.com/illegalstudio/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/Lazyagent.app/Contents/MacOS/lazyagent"

  # No zap stanza required

end
