# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  version "0.12.4"

  on_macos do
    on_intel do
      sha256 "3788cbb38cea8ef542b44d044e1513d7e4f03418b6c5fc580516cda033dd50c6"
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "12d40adf7ae7eec1a550b6d9763c0c7f2cb29f7ff79d327cdba9619ff4f8af2e"
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "bca13a67b432b039e7f3c2e06f3e6b7d45abb04cb55f7e0ac00922180abef935"
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "506461892aba7da1917938c44e90d5da3276e17e18a014e32bf3eaa44a3b9c53"
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyagent"
  desc "A lazy TUI for monitoring Claude Code agent sessions"
  homepage "https://github.com/illegalstudio/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  # No zap stanza required

end
