# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  name "lazyagent"
  desc "A lazy TUI for monitoring Claude Code agent sessions"
  homepage "https://github.com/illegalstudio/lazyagent"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  on_macos do
    on_intel do
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.tar.gz"
      sha256 "3c66543db32f558ebf263aaab37f82c23109fd7dc8c130a4216bb551c0036d61"
    end
    on_arm do
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.tar.gz"
      sha256 "046afeb41ad22a1079c081e7199585432fa132bbbe242bdf707ab04a12c9f6a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
      sha256 "70c0474e4f399860eba52146fc97ac822bb239445eb1b7c45ee4457bf20dec32"
    end
    on_arm do
      url "https://github.com/illegalstudio/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
      sha256 "5c04be4ec8b3fcc3a7325f572f2a858d4668ae74a6b5ed3906de77c82d453c92"
    end
  end

  # No zap stanza required
end
