# This file is generated by Mnemo's release CI. DO NOT EDIT.
cask "mnemo" do
  version "0.1.1"
  sha256 "f81dc78cbd556e949da036aa39e5b78153a9a80b3d176d738eac000f01bdb344"

  url "https://github.com/illegalstudio/mnemo/releases/download/v0.1.1/Mnemo_0.1.1_universal.dmg",
      verified: "github.com/illegalstudio/mnemo/"
  name "Mnemo"
  desc "Personal archive for AI chat conversations"
  homepage "https://github.com/illegalstudio/mnemo"

  app "Mnemo.app"

  zap trash: [
    "~/Library/Application Support/studio.illegal.mnemo",
    "~/Library/Caches/studio.illegal.mnemo",
    "~/Library/HTTPStorages/studio.illegal.mnemo",
    "~/Library/Preferences/studio.illegal.mnemo.plist",
    "~/Library/Saved Application State/studio.illegal.mnemo.savedState",
    "~/Library/WebKit/studio.illegal.mnemo",
  ]
end
